//=========================================================
// src/Interrupts.c: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================


// USER INCLUDES
#include <SI_EFM8UB2_Register_Enums.h>

// External variables for software PWM (defined in main.c)
extern volatile uint8_t motor_direction;
extern volatile uint8_t pwm_duty;
extern volatile uint8_t pwm_counter;

// Pin definitions for motor control
SI_SBIT(M1_ISR, SFR_P0, 4);
SI_SBIT(M2_ISR, SFR_P0, 5);

//-----------------------------------------------------------------------------
// TIMER2_ISR
//-----------------------------------------------------------------------------
//
// TIMER2 ISR Content goes here. Remember to clear flag bits:
// TMR2CN0::TF2H (Timer # High Byte Overflow Flag)
// TMR2CN0::TF2L (Timer # Low Byte Overflow Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER2_ISR, TIMER2_IRQn)
{

}


//-----------------------------------------------------------------------------
// SPI0_ISR
//-----------------------------------------------------------------------------
//
// SPI0 ISR Content goes here. Remember to clear flag bits:
// SPI0CN0::MODF (Mode Fault Flag)
// SPI0CN0::RXOVRN (Receive Overrun Flag)
// SPI0CN0::SPIF (SPI# Interrupt Flag)
// SPI0CN0::WCOL (Write Collision Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (SPI0_ISR, SPI0_IRQn)
{

}


//-----------------------------------------------------------------------------
// ADC0EOC_ISR
//-----------------------------------------------------------------------------
//
// ADC0EOC ISR Content goes here. Remember to clear flag bits:
// ADC0CN0::ADINT (Conversion Complete Interrupt Flag)
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (ADC0EOC_ISR, ADC0EOC_IRQn)
{

}


//-----------------------------------------------------------------------------
// TIMER3_ISR
//-----------------------------------------------------------------------------
//
// TIMER3 ISR Content goes here. Remember to clear flag bits:

//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER3_ISR, TIMER3_IRQn)
{

}



//-----------------------------------------------------------------------------
// TIMER0_ISR
//-----------------------------------------------------------------------------
//
// TIMER0 ISR - Software PWM for motor speed control
// Called frequently to generate PWM on M1/M2 pins
//
//-----------------------------------------------------------------------------
SI_INTERRUPT (TIMER0_ISR, TIMER0_IRQn)
{
    // Reload timer for consistent frequency
    TH0 = 0xFF;
    TL0 = 0x00;
    
    // Increment PWM counter (wraps at 256)
    pwm_counter++;
    
    // Software PWM logic
    if (motor_direction == 0) {
        // Motor stopped
        M1_ISR = 0;
        M2_ISR = 0;
    }
    else if (pwm_counter < pwm_duty) {
        // ON portion of PWM cycle
        if (motor_direction == 1) {
            M1_ISR = 1;  // Clockwise
            M2_ISR = 0;
        } else {
            M1_ISR = 0;
            M2_ISR = 1;  // Counterclockwise
        }
    }
    else {
        // OFF portion of PWM cycle
        M1_ISR = 0;
        M2_ISR = 0;
    }
}


